name: Student App CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-scan-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/student-backend:latest ./backend

      - name: Build Frontend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/student-frontend:latest ./frontend

      - name: Run Backend Unit Tests
        run: |
          docker run --rm ${{ secrets.DOCKER_USERNAME }}/student-backend:latest pytest

      - name: Security Scan (Trivy)
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/student-backend:latest
          severity: HIGH,CRITICAL
          format: table

      - name: Push Backend Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/student-backend:latest

      - name: Push Frontend Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/student-frontend:latest
