name: Student App CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      #  Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4

      #  Login to Docker Hub (using GitHub Secrets)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #  Build Backend Docker Image
      - name: Build Backend Image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/student-backend:latest \
            ./backend

      #  Build Frontend Docker Image
      - name: Build Frontend Image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/student-frontend:latest \
            ./frontend

      #  Security Scan Backend Image (Trivy)
      #  continue-on-error is IMPORTANT to avoid pipeline failure
      - name: Security Scan (Trivy)
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/student-backend:latest
          severity: HIGH,CRITICAL
          format: table

      # Push Backend Image to Docker Hub
      - name: Push Backend Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/student-backend:latest

      # Push Frontend Image to Docker Hub
      - name: Push Frontend Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/student-frontend:latest
